X509 Implementation and tests Reviewed
GJWT/OIDCMsg-NodeJS pull request #12
Opened 2018-01-08 22:33 UTC by anjuthomas

2018-01-09 22:53 UTC, lyzhang27 requested changes

2018-01-09 22:53 UTC, lyzhang27 commented on src/controllers/messageTypes/jwt/jsonwebtoken/decode.js
>  var jwtDecoder = JWTDecoder.prototype;
Should we remove this and just define functions with "JWTDecoder.prototype"?

2018-01-09 22:53 UTC, lyzhang27 commented on src/controllers/messageTypes/jwt/jsonwebtoken/decode.js
> +jwtDecoder.verifyJwtSign = function(token, secretOrPublicKey, tokenProfile, otherOptions, baseEncoding, callback){
JWTDecoder.prototype?

2018-01-09 22:53 UTC, lyzhang27 commented on src/controllers/messageTypes/jwt/jsonwebtoken/decode.js
> +}
Indentation is off here

2018-01-09 22:53 UTC, lyzhang27 commented on src/controllers/messageTypes/jwt/jsonwebtoken/decode.js
>  var jwkToPem          = require('jwk-to-pem');
Missing ";" in line 8

2018-01-09 22:53 UTC, lyzhang27 commented on src/controllers/messageTypes/jwt/jsonwebtoken/decode.js
> +      if (!valid){
Missing space after the ")"

2018-01-09 22:53 UTC, lyzhang27 commented on src/controllers/messageTypes/jwt/jsonwebtoken/decode.js
> +            //return jws.verify(token, jwt.header.alg, secretOrPublicKey, baseEncoding);
Why are these two lines commented out?

2018-01-09 22:53 UTC, lyzhang27 commented on src/controllers/messageTypes/jwt/jsonwebtoken/decode.js
>          }
Indentation is off here.

2018-01-09 22:53 UTC, lyzhang27 commented on test/x509-test.js
> +
This is an extra line.

2018-01-09 22:53 UTC, lyzhang27 commented on test/x509-test.js
> +
Extra line?

2018-01-09 22:53 UTC, lyzhang27 commented on test/x509-test.js
> +  var priv = fs.readFileSync("/Users/anjuthomas/Documents/example_key.pem");
We should not be checking in this local directory path

2018-01-09 22:53 UTC, lyzhang27 commented on test/x509-test.js
> +
Extra line

2018-01-09 22:53 UTC, lyzhang27 commented on test/x509-test.js
> +    var priv = fs.readFileSync("/Users/anjuthomas/Documents/example_key.pem");
We should not be checking in this absolute local path.

2018-01-09 22:53 UTC, lyzhang27 commented on test/x509-test.js
> +    var pub = fs.readFileSync("/Users/anjuthomas/Documents/rolandPub.pem");
We should not be checking in this absolute local path.

2018-01-09 22:53 UTC, lyzhang27 commented on test/x509-test.js
> +    var priv = fs.readFileSync("/Users/anjuthomas/Documents/rolandPriv.pem");
We should not be checking in this absolute local path.

2018-01-09 22:53 UTC, lyzhang27 commented on test/x509-test.js
> +
There are a couple of extra lines here.

2018-01-09 23:30 UTC, anjuthomas commented on src/controllers/messageTypes/jwt/jsonwebtoken/decode.js
>  var jwkToPem          = require('jwk-to-pem');
Done

2018-01-09 23:34 UTC, anjuthomas commented on src/controllers/messageTypes/jwt/jsonwebtoken/decode.js
>  var jwtDecoder = JWTDecoder.prototype;
Done

2018-01-09 23:34 UTC, anjuthomas commented on src/controllers/messageTypes/jwt/jsonwebtoken/decode.js
> +jwtDecoder.verifyJwtSign = function(token, secretOrPublicKey, tokenProfile, otherOptions, baseEncoding, callback){
Done

2018-01-09 23:35 UTC, anjuthomas commented on src/controllers/messageTypes/jwt/jsonwebtoken/decode.js
> +      if (!valid){
Done

2018-01-09 23:37 UTC, anjuthomas commented on src/controllers/messageTypes/jwt/jsonwebtoken/decode.js
> +}
Done

2018-01-09 23:38 UTC, anjuthomas commented on src/controllers/messageTypes/jwt/jsonwebtoken/decode.js
> +            //return jws.verify(token, jwt.header.alg, secretOrPublicKey, baseEncoding);
Removed

2018-01-09 23:42 UTC, anjuthomas commented on src/controllers/messageTypes/jwt/jsonwebtoken/decode.js
>          }
Done

2018-01-09 23:45 UTC, anjuthomas commented on test/x509-test.js
> +
Done

2018-01-09 23:45 UTC, anjuthomas commented on test/x509-test.js
> +
Done

2018-01-09 23:46 UTC, anjuthomas commented on test/x509-test.js
> +
Done

2018-01-09 23:57 UTC, anjuthomas commented on test/x509-test.js
> +    var priv = fs.readFileSync("/Users/anjuthomas/Documents/example_key.pem");
Done

2018-01-09 23:58 UTC, anjuthomas commented on test/x509-test.js
> +    var pub = fs.readFileSync("/Users/anjuthomas/Documents/rolandPub.pem");
Done

2018-01-09 23:58 UTC, anjuthomas commented on test/x509-test.js
> +  var priv = fs.readFileSync("/Users/anjuthomas/Documents/example_key.pem");
Done

2018-01-10 00:02 UTC, anjuthomas commented on test/x509-test.js
> +
Done

2018-01-10 00:02 UTC, anjuthomas commented on test/x509-test.js
> +    var priv = fs.readFileSync("/Users/anjuthomas/Documents/rolandPriv.pem");
Done

2018-01-11 02:15 UTC, lyzhang27 approved these changes

2018-01-11 17:00 UTC, merged